version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dpms_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: dpms
    ports:
      - "5432:5432"
    volumes:
      - dpms_pg_data:/var/lib/postgresql/data

volumes:
  dpms_pg_data: